// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://omzeqwgtxplmmeyaqetb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9temVxd2d0eHBsbW1leWFxZXRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1OTU1NzgsImV4cCI6MjA2NDE3MTU3OH0.a2cb_H9E2LH82k6WryDPqaDyhcLVTuePPJ86w_zQ3ZU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);